// @vitest-environment jsdom
//
// Verdict-page audit harness.
//
// Runs the REAL logic behind the product-detail (verdict) page across hundreds
// of synthetic products built from every brand the app knows about, and
// cross-checks every signal the page renders:
//
//   - top-line verdict            getVerdict() (OpenFoodFactsDetail)
//   - personalized numeric score  personalizedScore()
//   - labour allegations banner   findLaborAllegations()
//   - verified brand-flag banner  getVerifiedFlagsForBrand()
//   - boycott banner              checkBoycott()
//   - animal-welfare flag         checkAnimalWelfareFlag()
//   - verified-ethics green card  findVerifiedEthics()
//   - chocolate directory verdict findChocolateEntry()
//   - ingredient concerns         findIngredientFlagsInText()
//   - swap suggestions            the four candidate sources
//
// It fails when the app contradicts itself — e.g. a brand the app itself
// boycott-flags being recommended as an "ethical swap", or a matcher
// false-positive that would put a red banner on an innocent brand.
// A full findings report is written to docs/verdict-audit-report.md.

import { describe, it, expect, afterAll } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";

import { checkBoycott } from "@/data/boycottBrands";
import { findLaborAllegations } from "@/utils/laborCheck";
import { checkAnimalWelfareFlag } from "@/utils/animalWelfareFlags";
import { findVerifiedEthics, getVerifiedEthicsBrands } from "@/utils/verifiedEthics";
import { CHOCOLATE_DIRECTORY, findChocolateEntry } from "@/data/chocolateDirectory";
import { getVerifiedFlagsForBrand } from "@/services/brandFlags";
import { brandFlagsV2 } from "@/data/brandFlags.v2";
import { POOR_ANIMAL_WELFARE_COMPANIES } from "@/data/poorAnimalWelfareCompanies";
import {
  ETHICAL_ALTERNATIVES,
  SWAP_CATEGORY_KEYS,
  detectSwapCategory,
  type AltCandidate,
  type SwapCategoryKey,
} from "@/data/ethicalAlternatives";
import { getVerifiedEthicsCandidates } from "@/data/verifiedEthicsSwaps";
import { getChocolateDirectoryCandidates } from "@/data/chocolateDirectorySwaps";
import { getCustomCandidates } from "@/data/customSwaps";
import { personalizedScore, gradeFromScore, type Verdict } from "@/utils/personalizedScore";
import { DEFAULT_PRIORITIES, priorityMultiplier, type UserPriorities } from "@/utils/userPreferences";
import { getVerdict } from "@/pages/OpenFoodFactsDetail";
import { findIngredientFlagsInText } from "@/services/ingredientFlags";
import { INGREDIENT_FLAGS } from "@/data/ingredientFlags";
import type { OpenFoodFactsResult } from "@/services/openfoodfacts/types";

// ── Findings collector ───────────────────────────────────────────────────────

interface Finding {
  level: "ERROR" | "WARN" | "INFO";
  area: string;
  message: string;
}
const findings: Finding[] = [];
const report = (level: Finding["level"], area: string, message: string) => {
  findings.push({ level, area, message });
};

afterAll(() => {
  const lines: string[] = [
    "# Verdict-page audit report",
    "",
    `Generated by \`src/test/verdictPageAudit.test.ts\` on ${new Date().toISOString().slice(0, 10)}.`,
    "",
    `Totals: ${findings.filter(f => f.level === "ERROR").length} errors, ` +
      `${findings.filter(f => f.level === "WARN").length} warnings, ` +
      `${findings.filter(f => f.level === "INFO").length} notes.`,
    "",
  ];
  for (const level of ["ERROR", "WARN", "INFO"] as const) {
    const group = findings.filter(f => f.level === level);
    if (group.length === 0) continue;
    lines.push(`## ${level}`, "");
    for (const f of group) lines.push(`- **[${f.area}]** ${f.message}`);
    lines.push("");
  }
  const out = path.resolve(__dirname, "../../docs/verdict-audit-report.md");
  fs.writeFileSync(out, lines.join("\n"));
  // eslint-disable-next-line no-console
  console.log(`\n[verdict-audit] ${findings.length} findings → docs/verdict-audit-report.md`);
});

// ── Product + priority fixtures ──────────────────────────────────────────────

function makeProduct(over: Partial<OpenFoodFactsResult>): OpenFoodFactsResult {
  return {
    found: true,
    barcode: "0000000000000",
    productName: null,
    brand: null,
    ecoscoreGrade: null,
    ecoscoreScore: null,
    nutriscoreGrade: null,
    nutriscoreScore: null,
    novaGroup: null,
    carbonFootprint100g: null,
    carbonFootprintProduct: null,
    carbonFootprintServing: null,
    labels: [],
    categories: [],
    origins: null,
    ingredientsText: null,
    imageUrl: null,
    ecoscoreData: null,
    rawProduct: null,
    ...over,
  };
}

const P_DEFAULT: UserPriorities = { ...DEFAULT_PRIORITIES };
const P_ETHICS_CRITICAL: UserPriorities = { ...DEFAULT_PRIORITIES, laborRights: 80, animalWelfare: 80, environment: 50 };
const P_ECO_FOCUSED: UserPriorities = { ...DEFAULT_PRIORITIES, laborRights: 20, animalWelfare: 20, environment: 80 };
const PRIORITY_SETS: [string, UserPriorities][] = [
  ["default", P_DEFAULT],
  ["ethics-critical", P_ETHICS_CRITICAL],
  ["eco-focused", P_ECO_FOCUSED],
];

const VALID_VERDICTS = new Set(["BUY", "CONSIDER", "CAUTION", "AVOID", "UNKNOWN"]);
const BAND_RANK: Record<string, number> = { AVOID: 0, CAUTION: 1, CONSIDER: 2, BUY: 3 };

// Mirrors LABOUR_FLAG_CATEGORIES in src/services/swaps/index.ts.
const LABOUR_FLAG_CATEGORIES = new Set([
  "forced_labour", "child_labour", "wage_theft", "unsafe_conditions", "union_busting",
]);

// ── Brand universe ───────────────────────────────────────────────────────────

interface SourcedCandidate {
  candidate: AltCandidate;
  source: string;
  category: SwapCategoryKey;
}

function allSwapCandidates(): SourcedCandidate[] {
  const out: SourcedCandidate[] = [];
  for (const cat of SWAP_CATEGORY_KEYS) {
    for (const c of ETHICAL_ALTERNATIVES[cat]) out.push({ candidate: c, source: "catalog", category: cat });
    for (const c of getCustomCandidates(cat)) out.push({ candidate: c, source: "customSwaps", category: cat });
    for (const c of getVerifiedEthicsCandidates(cat)) out.push({ candidate: c, source: "verifiedEthics", category: cat });
    for (const c of getChocolateDirectoryCandidates(cat)) out.push({ candidate: c, source: "chocolateDirectory", category: cat });
  }
  return out;
}

/** Well-known brands a scanner realistically meets — extends the battery. */
const COMMON_SCANNED_BRANDS = [
  "Coca-Cola", "Pepsi", "Nestlé", "KitKat", "Nescafé", "Maggi", "Perrier",
  "Nutella", "Kinder", "Ferrero Rocher", "Oreo", "Cadbury", "Milka", "Toblerone",
  "Lay's", "Doritos", "Cheetos", "Walkers", "Pringles", "Tropicana", "Gatorade",
  "Ben & Jerry's", "Magnum", "Lipton", "Knorr", "Hellmann's", "Dove",
  "Starbucks", "McDonald's", "KFC", "Subway", "Domino's", "Burger King",
  "Hershey's", "Reese's", "Snickers", "M&M's", "Twix", "Mars",
  "Tyson", "Heinz", "Kraft", "Philadelphia", "Cheerios", "Yoplait",
  "Danone", "Activia", "Alpro", "Evian", "Tetley", "Folgers", "Lavazza", "illy",
  "Chiquita", "Dole", "Del Monte", "Barry Callebaut", "Godiva", "Lindt", "Lindor",
  "Ghirardelli", "Russell Stover", "Bumble Bee", "Chicken of the Sea",
  "Tony's Chocolonely", "Alter Eco", "Divine Chocolate", "Vital Farms",
  "Oatly", "Quorn", "Clipper Teas", "Cafédirect", "Wholesome Sweeteners",
  "Tate's Bake Shop", "Clif Bar", "Green & Black's", "Alpro", "Pukka Herbs",
  "Stonyfield Organic", "Surf Sweets", "So Delicious",
];

/** Innocent brands that must NOT trip any matcher (false-positive probes). */
const BENIGN_PROBES = [
  "Walkers Shortbread",       // independent Scottish maker, not PepsiCo's Walkers
  "Doves Farm",               // organic UK mill, not Unilever Dove / Mars Dove
  "Philly Swirl",             // contains "illy" — must not match illycaffè
  "Marshmallow Fluff",        // contains "mars…" — must not match Mars, Inc.
  "Contempo Coffee",          // contains "tempo" — must not match Tempo Beverages
  "Waxelene",                 // contains "axe" — must not match Unilever Axe
  "Elysian Fields Farm",      // contains "eli…" — must not match Strauss "Elite"
];
// (Tate's Bake Shop was originally probed as benign — wrongly: Mondelēz
// acquired it in 2018, so the Mondelēz match is CORRECT and it lives in the
// common-brand battery instead.)

function brandUniverse(): string[] {
  const set = new Set<string>();
  for (const { candidate } of allSwapCandidates()) set.add(candidate.brand);
  for (const b of getVerifiedEthicsBrands()) set.add(b.brandName);
  for (const e of CHOCOLATE_DIRECTORY) set.add(e.name);
  for (const c of POOR_ANIMAL_WELFARE_COMPANIES) {
    set.add(c.companyName);
    for (const b of c.brands) set.add(b);
  }
  for (const f of brandFlagsV2) set.add(f.brandName);
  for (const b of COMMON_SCANNED_BRANDS) set.add(b);
  for (const b of BENIGN_PROBES) set.add(b);
  return [...set];
}

// ── 1. Battery: every signal, hundreds of products ───────────────────────────

describe("verdict-page battery across the full brand universe", () => {
  const brands = brandUniverse();
  const ecoGrades: (string | null)[] = ["a", "c", "e", null];

  it(`runs ${brands.length} brands × ${ecoGrades.length} eco-grades × ${PRIORITY_SETS.length} priority sets without breaking invariants`, () => {
    let products = 0;

    for (const brand of brands) {
      const boycott = checkBoycott(brand);
      const labor = findLaborAllegations(brand, brand);
      const welfare = checkAnimalWelfareFlag(brand);

      for (const ecoscoreGrade of ecoGrades) {
        const product = makeProduct({ brand, productName: brand, ecoscoreGrade });
        products++;

        for (const [presetName, priorities] of PRIORITY_SETS) {
          const laborWeight = priorityMultiplier(priorities.laborRights);
          const animalWeight = priorityMultiplier(priorities.animalWelfare);

          // — top-line verdict —
          const verdict = getVerdict(product, priorities);
          expect(VALID_VERDICTS.has(verdict.key), `invalid verdict "${verdict.key}" for ${brand}`).toBe(true);
          expect(verdict.reason.length, `empty verdict reason for ${brand}`).toBeGreaterThan(0);

          // Hard rule: a boycott-listed brand can never read BUY while the
          // user cares about labour at all.
          if (boycott && laborWeight > 0 && verdict.key === "BUY") {
            report("ERROR", "verdict", `${brand} is boycott-listed (${boycott.parent}) but getVerdict says BUY (eco=${ecoscoreGrade}, ${presetName})`);
          }

          // Hard rule: ≥2 effective labour allegations force AVOID.
          const laborCount = labor?.allegations.length ?? 0;
          if (laborCount * laborWeight >= 2.0 && verdict.key !== "AVOID") {
            report("ERROR", "verdict", `${brand} has ${laborCount} labour allegations (weight ${laborWeight}) but verdict is ${verdict.key} (eco=${ecoscoreGrade}, ${presetName})`);
          }

          // Hard rule: critical animal-welfare flag + critical priority ⇒ never BUY.
          if (welfare.isFlagged && welfare.severity === "critical" && animalWeight >= 2.0 && verdict.key === "BUY") {
            report("ERROR", "verdict", `${brand} has a critical welfare flag but verdict is BUY (${presetName})`);
          }

          // — personalized numeric score —
          const ps = personalizedScore(
            { brand, productName: brand, ecoGrade: ecoscoreGrade, laborAllegations: laborCount },
            priorities,
          );
          if (ps.score !== null) {
            expect(ps.score, `score out of range for ${brand}`).toBeGreaterThanOrEqual(0);
            expect(ps.score, `score out of range for ${brand}`).toBeLessThanOrEqual(100);
            expect(Number.isInteger(ps.score), `non-integer score for ${brand}`).toBe(true);
            expect(ps.grade).toBe(gradeFromScore(ps.score));
            const expected: Verdict =
              ps.score >= 70 ? "BUY" : ps.score >= 45 ? "CONSIDER" : ps.score >= 25 ? "CAUTION" : "AVOID";
            expect(ps.verdict, `verdict/score band mismatch for ${brand}`).toBe(expected);
          } else {
            expect(ps.verdict).toBe("UNKNOWN");
          }

          // Score-side caps mirror the page rules.
          if (boycott && laborWeight >= 2.0 && ps.score !== null && ps.score > 40) {
            report("ERROR", "score", `${brand}: boycott + critical labour priority but score ${ps.score} > 40 (${presetName})`);
          }

          // — page ↔ score coherence (soft: bands should stay within 1 step) —
          if (ps.score !== null && verdict.key !== "UNKNOWN") {
            const gap = Math.abs(BAND_RANK[verdict.key] - BAND_RANK[ps.verdict]);
            if (gap >= 2) {
              report("WARN", "coherence", `${brand} (eco=${ecoscoreGrade}, ${presetName}): page verdict ${verdict.key} vs numeric verdict ${ps.verdict} (score ${ps.score})`);
            }
          }
        }
      }
    }

    expect(products).toBeGreaterThanOrEqual(400); // "hundreds of products"
  });

  it("suppresses the green verified-ethics card whenever a live red signal fires", () => {
    // Mirrors the page's cleanEthicsRecord gate: if this invariant is met the
    // page can never show a green all-clear under a red banner.
    for (const brand of brands) {
      const ethics = findVerifiedEthics(brand, brand);
      if (!ethics) continue;
      const boycott = checkBoycott(brand);
      const labor = findLaborAllegations(brand, brand);
      const welfare = checkAnimalWelfareFlag(brand);
      const red = !!boycott || !!labor || (welfare.isFlagged && (welfare.severity === "critical" || welfare.severity === "high"));
      if (red) {
        report("INFO", "green-vs-red", `${brand}: verified-ethics entry coexists with a red signal (${boycott ? "boycott" : labor ? "labour" : "welfare"}) — page suppresses the card, but the datasets disagree about this brand`);
      }
    }
  });
});

// ── 2. Recommended swaps must survive the app's own checks ───────────────────

describe("swap recommendations never contradict the app's own flags", () => {
  const sourced = allSwapCandidates();

  it(`screens all ${sourced.length} swap candidates against every negative signal`, () => {
    const errors: string[] = [];

    for (const { candidate: c, source, category } of sourced) {
      const boycott = checkBoycott(c.brand);
      const labor = findLaborAllegations(c.brand, c.productName);
      const welfare = checkAnimalWelfareFlag(c.brand);
      const v2 = getVerifiedFlagsForBrand(c.brand);
      const labourV2 = v2.filter(f => LABOUR_FLAG_CATEGORIES.has(f.category));
      const choc = findChocolateEntry(c.brand, c.productName);

      // The engine treats EVERY candidate as fixing a boycott concern
      // (candidateAddresses), so a boycott-listed candidate is always wrong.
      if (boycott) {
        errors.push(`[${source}/${category}] "${c.brand}" is boycott-listed (${boycott.parent}: ${boycott.reason})`);
      }
      if (c.addresses.includes("labor") && labor) {
        errors.push(`[${source}/${category}] "${c.brand}" is sold as a LABOUR swap but has ${labor.allegations.length} labour allegations via ${labor.parentCompany}`);
      }
      if (c.addresses.includes("labor") && labourV2.length > 0) {
        errors.push(`[${source}/${category}] "${c.brand}" is sold as a LABOUR swap but carries verified labour flag(s): ${labourV2.map(f => `${f.brandName} (${f.category})`).join(", ")}`);
      }
      if (c.addresses.includes("animal_welfare") && welfare.isFlagged && (welfare.severity === "critical" || welfare.severity === "high")) {
        errors.push(`[${source}/${category}] "${c.brand}" is sold as a WELFARE swap but ${welfare.company?.companyName} has a ${welfare.severity} welfare flag`);
      }
      if (category === "chocolate" && choc && (choc.verdict === "avoid" || choc.verdict === "caution")) {
        errors.push(`[${source}/${category}] "${c.brand}" is recommended, but the app's own Chocolate Directory rates ${choc.name} "${choc.verdict}"`);
      }

      // Softer signals: worth reviewing but not auto-contradictions.
      if (!boycott && labor && !c.addresses.includes("labor")) {
        report("WARN", "swaps", `[${source}/${category}] "${c.brand}" (non-labour swap) still matches labour allegations via ${labor.parentCompany}`);
      }
      if (v2.length > 0 && labourV2.length === 0) {
        report("WARN", "swaps", `[${source}/${category}] "${c.brand}" matches verified flag(s): ${v2.map(f => f.brandName).join(", ")}`);
      }
      if (welfare.isFlagged && welfare.severity === "moderate") {
        report("WARN", "swaps", `[${source}/${category}] "${c.brand}" matches a moderate welfare flag (${welfare.company?.companyName})`);
      }
    }

    for (const e of errors) report("ERROR", "swaps", e);
    expect(errors, `contradictory swap recommendations:\n${errors.join("\n")}`).toEqual([]);
  });

  it("the ranked swap output is screened at runtime too", async () => {
    // Even if a dirty entry sneaks into a catalog, the engine must not rank it.
    const { rankCategoryCandidates } = await import("@/services/swaps");
    for (const cat of SWAP_CATEGORY_KEYS) {
      for (const c of rankCategoryCandidates(cat, null)) {
        const boycott = checkBoycott(c.brand);
        const labor = findLaborAllegations(c.brand, c.productName);
        const welfare = checkAnimalWelfareFlag(c.brand);
        const dirty =
          !!boycott || !!labor ||
          (welfare.isFlagged && (welfare.severity === "critical" || welfare.severity === "high")) ||
          getVerifiedFlagsForBrand(c.brand).some(f => LABOUR_FLAG_CATEGORIES.has(f.category));
        if (dirty) {
          report("ERROR", "engine", `rankCategoryCandidates(${cat}) still returns red-flagged "${c.brand}"`);
        }
        expect(dirty, `engine ranked red-flagged candidate "${c.brand}" in ${cat}`).toBe(false);
      }
    }
  });

  it("keeps every candidate findable in its own category", () => {
    for (const { candidate: c, source, category } of sourced) {
      const detected = detectSwapCategory({ productName: c.productName, brand: c.brand });
      if (detected !== null && detected !== category) {
        report("WARN", "categories", `[${source}] "${c.productName}" lives in "${category}" but detectSwapCategory says "${detected}" — it could be offered in the wrong aisle`);
      }
    }
  });
});

// ── 3. Matcher false-positive probes ─────────────────────────────────────────

describe("brand matchers do not flag innocent brands", () => {
  it("benign probe brands trip no matcher", () => {
    const errors: string[] = [];
    for (const brand of BENIGN_PROBES) {
      const boycott = checkBoycott(brand);
      if (boycott) errors.push(`checkBoycott("${brand}") → ${boycott.parent}`);
      const labor = findLaborAllegations(brand, null);
      if (labor) errors.push(`findLaborAllegations("${brand}") → ${labor.parentCompany}`);
      const welfare = checkAnimalWelfareFlag(brand);
      if (welfare.isFlagged) errors.push(`checkAnimalWelfareFlag("${brand}") → ${welfare.company?.companyName}`);
      const v2 = getVerifiedFlagsForBrand(brand);
      if (v2.length > 0) errors.push(`getVerifiedFlagsForBrand("${brand}") → ${v2.map(f => f.brandName).join(", ")}`);
    }
    for (const e of errors) report("ERROR", "matchers", `false positive: ${e}`);
    expect(errors, `matcher false positives:\n${errors.join("\n")}`).toEqual([]);
  });

  it("cross-dataset identity: Domino's Pizza is not Domino Sugar", () => {
    const v2 = getVerifiedFlagsForBrand("Domino's Pizza");
    const wrong = v2.filter(f => f.brandName.includes("ASR"));
    if (wrong.length > 0) {
      report("ERROR", "matchers", `"Domino's Pizza" matches the ASR Group (Domino Sugar) labour flag — alias substring matching is too loose`);
    }
    expect(wrong).toEqual([]);
  });
});

// ── 4. Dataset integrity ─────────────────────────────────────────────────────

describe("dataset integrity", () => {
  it("brandFlags.v2: verified, sourced, dated, unique", () => {
    const names = new Set<string>();
    for (const f of brandFlagsV2) {
      expect(names.has(f.brandName), `duplicate flag for ${f.brandName}`).toBe(false);
      names.add(f.brandName);
      expect(f.status, `${f.brandName} not verified`).toBe("verified");
      expect(f.sources.length, `${f.brandName} has no sources`).toBeGreaterThan(0);
      for (const s of f.sources) {
        expect(s.url, `${f.brandName} source without https URL: "${s.url}"`).toMatch(/^https?:\/\//);
      }
      expect(f.lastVerified, `${f.brandName} bad lastVerified "${f.lastVerified}"`).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      for (const a of f.brandAliases ?? []) {
        expect(a, `alias "${a}" of ${f.brandName} should be lowercase/trimmed`).toBe(a.toLowerCase().trim());
      }
    }
  });

  it("poor-animal-welfare companies: unique ids, no brand claimed by two companies", () => {
    const ids = new Set<string>();
    const brandOwner = new Map<string, string>();
    for (const c of POOR_ANIMAL_WELFARE_COMPANIES) {
      expect(ids.has(c.id), `duplicate company id ${c.id}`).toBe(false);
      ids.add(c.id);
      expect(["critical", "high", "moderate"]).toContain(c.severity);
      for (const b of c.brands) {
        const key = b.toLowerCase();
        if (brandOwner.has(key)) {
          report("ERROR", "datasets", `brand "${b}" is claimed by both ${brandOwner.get(key)} and ${c.companyName}`);
        }
        brandOwner.set(key, c.companyName);
      }
    }
  });

  it("poor-animal-welfare companies: Whole Foods is not a Walmart brand", () => {
    const walmart = POOR_ANIMAL_WELFARE_COMPANIES.find(c => c.id === "walmart");
    const wrong = walmart?.brands.some(b => /whole foods/i.test(b)) ||
      walmart?.concerns.some(t => /whole foods/i.test(t));
    if (wrong) {
      report("ERROR", "datasets", `Walmart entry claims Whole Foods (owned by Amazon — the app's own Chocolate Directory says "Whole Foods (Amazon)")`);
    }
    expect(wrong, "Whole Foods misattributed to Walmart").toBeFalsy();
  });

  it("chocolate directory: unique names, valid verdicts", () => {
    const names = new Set<string>();
    for (const e of CHOCOLATE_DIRECTORY) {
      expect(names.has(e.name), `duplicate chocolate entry ${e.name}`).toBe(false);
      names.add(e.name);
      expect(["avoid", "caution", "better", "leader"]).toContain(e.verdict);
    }
  });

  it("swap catalog: valid concerns and market codes", () => {
    for (const { candidate: c, source, category } of allSwapCandidates()) {
      expect(c.addresses.length, `[${source}/${category}] "${c.brand}" addresses nothing`).toBeGreaterThan(0);
      for (const a of c.addresses) {
        expect(["labor", "boycott", "animal_welfare", "eco"]).toContain(a);
      }
      for (const m of c.markets ?? []) {
        expect(m, `[${source}] "${c.brand}" bad market code "${m}"`).toMatch(/^[A-Z]{2}$/);
      }
    }
  });

  it("ingredient flags: unique ids, and the page's cocoa-suppression id exists", () => {
    const ids = new Set<string>();
    for (const f of INGREDIENT_FLAGS) {
      expect(ids.has(f.id), `duplicate ingredient flag id ${f.id}`).toBe(false);
      ids.add(f.id);
    }
    // OpenFoodFactsDetail filters this exact id when a chocolate-directory entry
    // is shown; if it drifts, users see the same cocoa warning twice.
    expect(ids.has("cocoa-child-labour-west-africa")).toBe(true);

    const flags = findIngredientFlagsInText(
      "cocoa butter, cane sugar, palm oil, soy lecithin, vanilla extract, hazelnuts, coffee, black tea, shrimp powder, beef extract",
    );
    const seen = new Set(flags.map(f => f.id));
    expect(seen.size).toBe(flags.length); // no duplicate cards
    expect(flags.length).toBeGreaterThanOrEqual(5); // the classic risk ingredients all fire
  });
});
