// Marks output that came from a language model rather than from a source.
//
// The AI path (server.js -> /api/chatgpt/analyze-product, gpt-4o-mini) produces
// a labour risk level, A-E scores and suggested alternatives from the model's
// training knowledge. There are no citations behind any of it, and there is no
// way for the model to tell us which parts it is confident about for good
// reasons and which parts it has simply asserted fluently.
//
// It used to render in the same visual language as tier-1-sourced flags,
// including a green ShieldCheck "high confidence" pill. That pill was the
// model's self-report about its own certainty, styled identically to the badge
// the app uses for a US Department of Labor finding. A user had no way to tell
// them apart, and the more confident the model sounded, the more verified it
// looked.
//
// Deliberately NOT built from the same primitives as LaborFlagBanner. Sharing a
// component is how the two would drift back into looking alike.

import { Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { DS } from "@/styles/design-tokens";

interface Props {
  /** The model's own confidence self-report, shown as exactly that. */
  confidence?: string | null;
  /** What the model said it was unsure about. */
  disclaimer?: string | null;
  compact?: boolean;
}

export function AiEstimateBanner({ confidence, disclaimer, compact = false }: Props) {
  if (compact) {
    return (
      <span
        style={{
          display: "inline-flex", alignItems: "center", gap: 4,
          borderRadius: 999, padding: "3px 8px",
          border: `1px dashed ${DS.muted}`, background: "transparent",
          fontSize: 10, fontWeight: 700, color: DS.muted,
          fontFamily: DS.font, letterSpacing: "0.01em",
        }}
      >
        <Sparkles size={9} /> AI estimate
      </span>
    );
  }

  return (
    <div
      style={{
        // Dashed, uncoloured, no icon chip. Nothing here should read as a badge.
        border: `2px dashed ${DS.muted}`,
        borderRadius: 16,
        background: "transparent",
        padding: "14px 16px",
      }}
    >
      <div style={{ display: "flex", alignItems: "flex-start", gap: 10 }}>
        <Sparkles size={16} style={{ color: DS.muted, flexShrink: 0, marginTop: 1 }} />
        <div style={{ flex: 1, minWidth: 0 }}>
          <p style={{ fontSize: 13.5, fontWeight: 800, color: DS.ink, margin: "0 0 4px" }}>
            AI estimate — not source-verified
          </p>
          <p style={{ fontSize: 12, color: DS.muted, lineHeight: 1.55, margin: 0 }}>
            Everything below was generated by a language model from its training data. It has no
            citations, it has not been checked against any source, and it can be confidently wrong.
            Treat it as a starting point for your own research, not as a finding.
          </p>

          {confidence && (
            <p style={{ fontSize: 11.5, color: DS.muted, lineHeight: 1.55, margin: "8px 0 0" }}>
              The model rated its own confidence as <strong style={{ color: DS.ink2 }}>{confidence}</strong>.
              That is the model's opinion of itself, not a measure of accuracy.
            </p>
          )}

          {disclaimer && (
            <p style={{ fontSize: 11.5, color: DS.muted, lineHeight: 1.55, margin: "6px 0 0", fontStyle: "italic" }}>
              It flagged: {disclaimer}
            </p>
          )}

          <Link
            to="/methodology"
            style={{
              display: "inline-block", marginTop: 8,
              fontSize: 11.5, fontWeight: 700, color: DS.ink,
              textDecoration: "underline", textUnderlineOffset: 2,
            }}
          >
            How this differs from our sourced data →
          </Link>
        </div>
      </div>
    </div>
  );
}
